package automod_legacy

// This list is in alphabethical order
// Open a pr or bug me on discord if you want a word added
var BuiltinSwearWords = map[string]bool{
	"anal":        true,
	"anus":        true,
	"arse":        true,
	"ass":         true,
	"b1tch":       true,
	"ballsack":    true,
	"bastard":     true,
	"bitch":       true,
	"biatch":      true,
	"blowjob":     true,
	"bollock":     true,
	"bollok":      true,
	"boner":       true,
	"boob":        true,
	"boobs":       true,
	"buttplug":    true,
	"clitoris":    true,
	"cock":        true,
	"cum":         true,
	"cunt":        true,
	"dick":        true,
	"dildo":       true,
	"dyke":        true,
	"erection":    true,
	"fag":         true,
	"faggot":      true,
	"feck":        true,
	"fellate":     true,
	"fellatio":    true,
	"felching":    true,
	"fuck":        true,
	"fucks":       true,
	"fudgepacker": true,
	"genitals":    true,
	"hell":        true,
	"jerk":        true,
	"jizz":        true,
	"knobend":     true,
	"labia":       true,
	"masturbate":  true,
	"muff":        true,
	"nigger":      true,
	"nigga":       true,
	"penis":       true,
	"piss":        true,
	"poop":        true,
	"pube":        true,
	"pussy":       true,
	"queer":       true,
	"scrotum":     true,
	"sex":         true,
	"shit":        true,
	"sh1t":        true,
	"slut":        true,
	"smegma":      true,
	"spunk":       true,
	"tit":         true,
	"tranny":       true,
	"trannies":     true,
	"tosser":      true,
	"turd":        true,
	"twat":        true,
	"vagina":      true,
	"wank":        true,
	"whore":       true,
	"tits":        true,
	"titty":       true,
	"asshole":     true,
	"fvck":        true,
	"asshat":      true,
	"pu55y":       true,
	"pen1s":       true,
	'а' => ['а', 'a', '@'],
  	'б' => ['б', '6', 'b'],
  	'в' => ['в', 'b', 'v'],
  	'г' => ['г', 'r', 'g'],
  	'д' => ['д', 'd', 'g'],
  	'е' => ['е', 'e'],
  	'ё' => ['ё', 'е', 'e'],
  	'ж' => ['ж', 'zh', '*'],
  	'з' => ['з', '3', 'z'],
  	'и' => ['и', 'u', 'i'],
  	'й' => ['й', 'u', 'y', 'i'],
  	'к' => ['к', 'k', 'i{', '|{'],
  	'л' => ['л', 'l', 'ji'],
  	'м' => ['м', 'm'],
  	'н' => ['н', 'h', 'n'],
  	'о' => ['о', 'o', '0'],
  	'п' => ['п', 'n', 'p'],
  	'р' => ['р', 'r', 'p'],
  	'с' => ['с', 'c', 's'],
  	'т' => ['т', 'm', 't'],
  	'у' => ['у', 'y', 'u'],
  	'ф' => ['ф', 'f'],
 	'х' => ['х', 'x', 'h', 'к', 'k', '}{'],
 	'ц' => ['ц', 'c', 'u,'],
 	'ч' => ['ч', 'ch'],
 	'ш' => ['ш', 'sh'],
 	'щ' => ['щ', 'sch'],
 	'ь' => ['ь', 'b'],
 	'ы' => ['ы', 'bi'],
 	'ъ' => ['ъ'],
 	'э' => ['э', 'е', 'e'],
  	'ю' => ['ю', 'io'],
  	'я' => ['я', 'ya'],
}
